name: Despliegue en el servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_SERVER: ${{ secrets.SSH_SERVER }}
      SSH_AUTH_SOCK: ${{ runner.ssh_auth_sock }}

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar clave SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
      shell: bash

    - name: Iniciar agente SSH
      run: |
        eval `ssh-agent -s`
        ssh-add key.pem
      shell: bash

    - name: Verificar agent SSH
      run: ssh-add -l

    - name: Ejecutar comandos en el servidor
      run: |
        ssh -o StrictHostKeyChecking=no -A $SSH_USERNAME@$SSH_SERVER "touch /home/matijego/gitactions.txt"
      shell: bash
