name: SSH Login

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 190.220.47.69 >> ~/.ssh/known_hosts

      - name: SSH Login
        run: ssh -i ~/.ssh/id_rsa pi@190.220.47.69
        
      - name: Comandos
        run: |
          echo "This is an additional command"
          touch holadesdegit.txt
