name: SSH Login

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: cross-the-world/ssh-pipeline@master

      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: 190.220.47.69
          user: pi
          pass: X827i&oJWpqxR7Bv
          connect_timeout: 10s
          script: |
            (rm -rf /home/github/test || true)
            ls -la  
            echo $WELCOME 
            mkdir -p /home/github/test/test1 && 
            mkdir -p /home/github/test/test2 &&
