name: Despliegue en el servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_SERVER: ${{ secrets.SSH_SERVER }}

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Iniciar agente SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add key.pem
        ssh-add -l

    - name: Ejecutar comandos en el servidor
      run: |
        ssh -o StrictHostKeyChecking=no -A $SSH_USERNAME@$SSH_SERVER "touch gitactions.txt"
        ssh -o StrictHostKeyChecking=no -A $SSH_USERNAME@$SSH_SERVER "touch gitactions2.txt"
